# Etapa 1: Construcción de la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 7600

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["API/API.csproj", "API/"]
RUN dotnet restore "API/API.csproj"
COPY . .
WORKDIR "/src/API"
RUN dotnet build "API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish

# Etapa 2: Construcción del contenedor final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Copiar el archivo appsettings.json
COPY API/appsettings.json /app/
COPY API/dating.db /app/

# Configurar variables de entorno
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "API.dll"]
